djangotest1/mypro/myapp/urls.py
from django.conf.urls import url
from . import views

app_name = 'myapp'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^hello/$', views.hello, name='hello'),
    url(r'^test/$', views.test, name='test'),
    url(r'^listfield/$', views.listfield, name='listfield'),
    url(r'^listfield1/$', views.listfield1, name='listfield1'),
    url(r'^listfield2/$', views.listfield2, name='listfield2'),
    url(r'^query/$', views.query, name='query'),
    url(r'^mline/$', views.mline, name='mline'),
    url(r'^scale/$', views.scale, name='scale'),
    url(r'^mp/$', views.mp, name='mp'),
    url(r'^plot/$', views.plot, name='plot'),
    url(r'^plot1/$', views.plot1, name='plot1'),
    url(r'^ys/$', views.ys, name='ys'),
    url(r'^remove/$', views.remove, name='remove'),
    url(r'^changeall/$', views.changeall, name='changeall'),
    url(r'^c3/$', views.c3, name='c3'),
    url(r'^rep/$', views.rep, name='rep'),
    url(r'^rep1/$', views.rep1, name='rep1'),
    url(r'^datatable/$', views.datatable, name='datatable'),
    url(r'^bokeh/$', views.bokeh, name='bokeh'),
]

djangotest1/mypro/mypro/urls.py
from django.conf.urls import include, url
from django.contrib import admin
urlpatterns = [
    url(r'^myapp/', include('myapp.urls')),
    url(r'^admin/', admin.site.urls),
]

djangotest1/mypro/myapp/models.py
from django.db import models

# Create your models here.

djangotest1/mypro/myapp/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse

from django.shortcuts import render, redirect

from pandas import *
from numpy import *
from sqlite3 import *
import os
path = 'C:/Users/ak66h_000/Documents/db/'
os.chdir(path)

from bokeh.plotting import figure
from bokeh.embed import components

import datetime

epoch = datetime.datetime.utcfromtimestamp(0)

def unix_time_millis(dt):
    return (dt - epoch).total_seconds() * 1000.0

# d = datetime.datetime(2012, 10, 1)
# unix_time_millis(d)
# datetime.datetime(df['年月'])
# df['年月']=to_datetime(df['年月'])
# df['年月']=df['年月'].apply(unix_time_millis)


def hello(request):
    return render(request, 'myapp/hello.html')
#
#
# @app.route('/', methods=['GET', 'POST'])
# def home():
#     return '<h1>Home</h1>'
#
# @app.route('/signin', methods=['GET'])
# def signin_form():
#     return '''<form action="/signin" method="post">
#               <p><input name="username"></p>
#               <p><input name="password" type="password"></p>
#               <p><button type="submit">Sign In</button></p>
#               </form>'''
#
# @app.route('/signin', methods=['POST'])
# def signin():
#     # 需要从request对象读取表单内容：
#     if request.form['username']=='admin' and request.form['password']=='password':
#         return '<h3>Hello, admin!</h3>'
#     return '<h3>Bad username or password.</h3>'
#
# @app.route('/test', methods=['GET'])
# def index():
#     return '''<form action="/test" method="post">
#               <input type="text" name="username" value='1'>
#               <input type="text" name="username" value='2'>
#               <p><button type="submit">run</button></p>
#               </form>'''
#
# @app.route('/test', methods=['POST'])
# def test():
#     print(request.form.getlist('username'))
#     return '{}'.format(request.form.getlist('username'))  # only text type can get value

database = 'mops'
conn = connect('{}.sqlite3'.format(database))
c = conn.cursor()
mops = []
c.execute("SELECT name FROM sqlite_master WHERE type='table';")
for i in range(len(c.fetchall())):
    c.execute("SELECT name FROM sqlite_master WHERE type='table';")
    tb = c.fetchall()[i][0]
    mops.append(tb)

database = 'mysum'
conn = connect('{}.sqlite3'.format(database))
c = conn.cursor()
mysum = []
c.execute("SELECT name FROM sqlite_master WHERE type='table';")
for i in range(len(c.fetchall())):
    c.execute("SELECT name FROM sqlite_master WHERE type='table';")
    tb = c.fetchall()[i][0]
    mysum.append(tb)

database = 'summary'
conn = connect('{}.sqlite3'.format(database))
c = conn.cursor()
summary = []
c.execute("SELECT name FROM sqlite_master WHERE type='table';")
for i in range(len(c.fetchall())):
    c.execute("SELECT name FROM sqlite_master WHERE type='table';")
    tb = c.fetchall()[i][0]
    summary.append(tb)

database = 'tse'
conn = connect('{}.sqlite3'.format(database))
c = conn.cursor()
tse = []
c.execute("SELECT name FROM sqlite_master WHERE type='table';")
for i in range(len(c.fetchall())):
    c.execute("SELECT name FROM sqlite_master WHERE type='table';")
    tb = c.fetchall()[i][0]
    tse.append(tb)

dic = dict()
for i in mops:
    dic[i] = 'mops'
for i in mysum:
    dic[i] = 'mysum'
for i in summary:
    dic[i] = 'summary'
for i in tse:
    dic[i] = 'tse'

d = dict()

def index(request):
    global d
    d['mops'], d['mysum'], d['summary'], d['tse'] = mops, mysum, summary, tse
    d['mops1'], d['mysum1'], d['summary1'], d['tse1'] = mops, mysum, summary, tse
    l = request.POST.getlist('choice')   #list object, empty is allowed
    d['l'] = l
    for i in l:
        print(i)
    d['tab'] = '#tabs-1'
    print(d)
    return render(request, 'myapp/testlist.html', d)

def listfield(request):
    global tab
    tab ='#tabs-1'
    d['tab'] = tab
    if request.method == 'POST':
        global df, dbtable
        dbtable = request.form['dbtable']  # string object, empty is not allowed
        conn = connect('{}.sqlite3'.format(dic[dbtable]))
        df = read_sql_query("SELECT * from `{}`".format(dbtable), conn)
        d['fields'] = list(df)
        return render(request, 'myapp/testlist.html', d)
    else:
        return render(request, 'myapp/testlist.html', d)

def listfield1(request):
    global tab
    tab ='#tabs-5'
    d['tab'] = tab
    if request.method == 'POST':
        global df, dbtable1
        dbtable1 = request.form['dbtable1']  # string object, empty is not allowed
        conn = connect('{}.sqlite3'.format(dic[dbtable1]))
        df = read_sql_query("SELECT * from `{}`".format(dbtable1), conn)
        d['fields1'] = list(df)
        return render(request, 'myapp/testlist.html', d)
    else:
        return render(request, 'myapp/testlist.html', d)

def listfield2(request):
    global tab, fields2
    tab ='#tabs-7'
    d['tab'] = tab
    if request.method == 'POST':
        global df, dbtable2
        dbtable2 = request.form['dbtable2']  # string object, empty is not allowed
        conn = connect('{}.sqlite3'.format(dic[dbtable2]))
        df = read_sql_query("SELECT * from `{}`".format(dbtable2), conn)
        fields2 = list(df)
        d['fields2'] = fields2
        return render(request, 'myapp/testlist.html', d)
    else:
        return render(request, 'myapp/testlist.html', d)

def query(request):
    global mll, df, df1
    cols = request.form.getlist('cols')   # list object, empty is allowed
    d['cols'] = cols
    if '年月日' in cols:
        cols.remove('年月日')
        cols.insert(0, '年月日')
    else:
        cols.insert(0, '年月日')

    for i in cols:
        print(i)

    database = 'mysum'
    conn = connect('{}.sqlite3'.format(database))
    c = conn.cursor()
    table = 'forr'
    df = read_sql_query('select `{}` from `{}`'.format('`,`'.join(cols), table), conn)
    df = df[cols]
    df['年月日'] = to_datetime(df['年月日'])
    df['年月日'] = df['年月日'].apply(unix_time_millis)
    df = df.dropna(subset=['年月日'])
    df1 = df.copy()
    l = array(df1).tolist()
    d['data'] = [['NaN' if isnull(x) else x for x in i] for i in l]
    d['labels'] = list(df1)
    d['y'] = list(df1)[1:]
    d['ymd'] = df1.年月日.tolist()
    list(df1)
    d['tab'] = '#tabs-2'
    return render(request, 'myapp/testlist.html', d)

mll, mll1 = [], []
i=0
j=0

def mline(request):
    global i, j, mll, mll1, tab, d
    j += 1
    # global df
    # global df1
    cols = request.form.getlist('cols')   # list object, empty is allowed
    # d['cols'] = cols
    if '年月日' in cols:
        cols.remove('年月日')
        cols.insert(0, '年月日')
    else:
        cols.insert(0, '年月日')

    for c in cols:
        print(c)

    # database = 'mysum'
    # conn = connect('{}.sqlite3'.format(database))
    # table = 'forr'
    # c = conn.cursor()
    # # cols=['年月日', '開盤價', '最高價']
    # df = read_sql_query('select `{}` from `{}`'.format('`,`'.join(cols), table), conn)
    # df = df[cols]
    conn = connect('{}.sqlite3'.format(dic[dbtable]))
    df = read_sql_query("SELECT `{}` from `{}`".format('`,`'.join(cols), dbtable), conn)
    list(df)
    df.ix[:, 1:] = df.ix[:, 1:].astype(float)
    d['labels'] = list(df)
    d['data'] = array(df).tolist()
    df['年月日'] = to_datetime(df['年月日'])
    df['年月日'] = df['年月日'].apply(unix_time_millis)
    df = df.dropna(subset=['年月日']).dropna(subset=cols[1:])
    df1 = df.copy()
    l = array(df1).tolist()
    data = [['NaN' if isnull(x) else x for x in i] for i in l]
    data = str(data).replace('NaN', "null").replace("'", "")
    # str(['NaN', 2]).replace('NaN',"null").replace("'","")
    labels = list(df1)
    y = list(df1)[1:]
    ymd = df1.年月日.tolist()
    list(df1)
    width = request.form['width']
    height = request.form['height']
    try:
        rangeselector = request.form['rangeselector']
    except:
        rangeselector = 'false'
        pass
    print(rangeselector)
    mll.append([j, cols, data, labels, y, ymd, df1, width, height, rangeselector])
    mll1.append([j, cols, data, labels, y, ymd, df1, width, height, rangeselector])
    d['mll'] = mll1
    tab ='#tabs-2'
    d['tab'] = tab
    d['tableid']='true'
    # l=array(df).tolist()
    # d['q'] =[list(df)]+[['NaN' if isnull(x) else x for x in i] for i in l]
    # return render(request, 'myapp/c3.html', d)
    return render(request, 'myapp/testlist.html', d)
    # return render(request, 'myapp/dygraph.html', d)

# @app.route('/scale/', methods=['POST'])
# def scale():
#     df1 = df.copy()
#     print(df)
#     if request.form['dy'] == 'raw':
#         df1 = df.copy()
#     if request.form['dy'] == 'normalize':
#         df1.ix[:, 1:] = df.ix[:, 1:].apply(lambda x: (x - x.mean()) / x.std()).copy()
#     print(df1)
#     l = array(df1).tolist()
#     d['data'] = [['NaN' if isnull(x) else x for x in i] for i in l]
#     d['labels'] = list(df1)
#     d['y'] = list(df1)[1:]
#     return render(request, 'myapp/testlist.html', d)

def scale(request):
    global mll, mll1, tab
    for i, l in enumerate(mll1):
        try:
# without try, program will break if request.form['dy'+str(l[0])] is invalid
            if request.form['dy'+str(l[0])] == 'raw':
                mll1[i][6] = mll[i][6].copy()
                print(mll[i][6])
                print(i)
                print(mll1[i][6].ix[:, 1:])
                li = array(mll1[i][6]).tolist()
                mll1[i][2] = [['NaN' if isnull(x) else x for x in a] for a in li].copy()
                print(request.form['dy'+str(l[0])])
                d['mll'] = mll1
                return render(request, 'myapp/testlist.html', d)

            if request.form['dy'+str(l[0])] == 'normalize':
                df = mll1[i][6].copy()
                print(df.ix[:, 1:].apply(lambda x: (x - x.mean()) / x.std()).copy())
                df.ix[:, 1:] = df.ix[:, 1:].apply(lambda x: (x - x.mean()) / x.std()).copy()
                mll1[i][6] = df.copy()
                # mll1[l[0]][6].ix[:, 1:] = mll[l[0]][6].ix[:, 1:].apply(lambda x: (x - x.mean()) / x.std()).copy()

                print(mll1[i][6])

djangotest1/mypro/myapp/templates/myapp/index0.html
<!DOCTYPE html>
<html>
    <head>
        <title>I come from template!!</title>
        <style>
            body {
               background-color: lightyellow;
            }
            em {
                color: LightSeaGreen;
            }
        </style>
    </head>
    <body>
        <h1>Hello World!</h1>
        {{ test }}

        <form action="{% url 'myapp:test'%}" method="post">
        {% csrf_token %}
        <input type="checkbox" name="choice" value="Bike">
        <input type="checkbox" name="choice" value="Car">
        <input type="submit" value="Vote">
        </form>

    {% for item in l %}
    {{ item }}<br>
    {% endfor %}
    </body>
</html>

djangotest1/mypro/myapp/templates/myapp/mline.html
<script>

  $(document).ready(function(){
    $('.remove').click(function(){
      //$('[name='+$(this).val()+']').remove();
      //$('#'+$(this).val()).remove();
      $(this).parent().remove();
      //$('#'+$(this).attr('name')).remove();
      });
});  
    
</script>

{% for l in d.mll %}
<!--<div id = dy{{l.0|safe}} style="width:1800px; height:700px;"></div>-->
<div id = dy{{l.0|safe}} style="width:{{l.7|safe}}px; height:{{l.8|safe}}px;" class='few'></div>
        <form action = "/scale/" method = "POST">
            <input type="submit" name=dy{{l.0|safe}} value="raw">
            <input type="submit" name=dy{{l.0|safe}} value="normalize">
            <input type="submit" name=dy{{l.0|safe}} value="remove" class=remove>
        </form>
        <!--<button class=remove name=dy{{l.0|safe}} value=dy{{l.0|safe}}>remove</button>-->
{% endfor %}

<script>
gs = [];
{% for l in d.mll %}
    var g{{l.0|safe}} = new Dygraph(document.getElementById('dy{{l.0|safe}}'),
          {{l.2|safe}},
          {
            labels: {{l.3|safe}},
            axes: {
                x: {
                    valueFormatter: Dygraph.dateString_,
                    axisLabelFormatter: Dygraph.dateAxisFormatter,
                    ticker: Dygraph.dateTicker
                }
          },
          highlightSeriesOpts: {
          strokeWidth: 1,
          strokeBorderWidth: 1,
          highlightCircleSize: 5
          },
          showRangeSelector: {{l.9|safe}},
          <!--labelsDivWidth:1600,-->
          legend: 'follow',
          labelsSeparateLines:true,
          connectSeparatedPoints:true
          });
gs.push(
        
        g{{l.0|safe}}
        
        );        
{% endfor %}
//var sync = Dygraph.synchronize(gs,{range: false});
</script>

<script>
  $(document).ready(function(){
    $('#sy').click(function(){
      alert(1);
var sync = Dygraph.synchronize(gs,{range: false});
      });
        $('#dsy').click(function(){
      alert(0);
var sync = Dygraph.synchronize(gs,{selection: false, zoom:false});
      });
});   
  
</script>

<script>
  $(function(){
    $('#tabs a[href="{{d.tab|safe}}"]').click();
  });
</script>

djangotest1/mypro/myapp/templates/myapp/mp.html
<script>
//$(document).ready(function(){
  //var i = 1;
  //$("#div7 input").click(function(){
  
  
  {% for l in d.L1 %}
    $("#div13").append('<div id = graphdiv'+{{l.0|safe}}+' class=inline style="width:450px;"></div>');
    //alert(i);

    new Dygraph(document.getElementById("graphdiv"+{{l.0|safe}}),
              {{l.2|safe}},
              {
                labels: {{l.3|safe}},
                title:'{{l.6|safe}}',
                axes: {
                    x: {
                        valueFormatter: Dygraph.dateString_,
                        axisLabelFormatter: Dygraph.dateAxisFormatter,
                        ticker: Dygraph.dateTicker
                    }
              },
              //showRangeSelector: true,
              legend: 'follow',
              labelsSeparateLines:true,
              connectSeparatedPoints:false
              });


      {% endfor %}
      $( function(){
        //$('#tabs a[href="#tabs-5"]').click();
        $('#tabs a[href="{{d.tab|safe}}"]').click();

      });
  //});  
//});  
  
</script>

djangotest1/mypro/myapp/templates/myapp/plot1.html
<script>
//$(document).ready(function(){
  //var i = 1;
  //$("#div7 input").click(function(){
  {% for l in d.L %}
    $("#div9").append('<div id = graphdiv'+{{l.0|safe}}+'></div>');
    //alert(i);

    new Dygraph(document.getElementById("graphdiv"+{{l.0|safe}}),
              {{l.2|safe}},
              {
                labels: {{l.3|safe}},
                title:'{{l.6|safe}}',
                axes: {
                    x: {
                        valueFormatter: Dygraph.dateString_,
                        axisLabelFormatter: Dygraph.dateAxisFormatter,
                        ticker: Dygraph.dateTicker
                    }
              },
              //showRangeSelector: true,
              legend: 'follow',
              labelsSeparateLines:true,
              connectSeparatedPoints:false
              });
    //$('body').append('<div id = graphdiv'+i+'></div>');

              //new Dygraph(document.getElementById("graphdiv"+i),
              //  [
              //    [1,10,100],
              //    [2,20,80],
              //    [3,50,60],
              //    [4,70,80]
              //  ],
              //  {
              //    labels: [ "x", "A", "B" ],
              //    showRangeSelector: true,
              //    valueRange: [20, 100],
              //    showRoller: true,
              //    rollPeriod: 15
              //  });
      //$('#graphdiv'+i).append(i);
      //i+=1;

      {% endfor %}
      $( function(){
        //$('#tabs a[href="#tabs-3"]').click();
        $('#tabs a[href="{{d.tab|safe}}"]').click();
      });
  //});  
//});  
  
</script>

djangotest1/mypro/myapp/templates/myapp/table.html
    <div id="tabs-9" class="tab-pane">

        <form action = "/rep1/" method = "POST">
            公司代號:<input type="text" name=compid_report1 value=5522>
            <input type="submit" value="query" id=sel>
            {% if d.report1 is defined %}
            <span id=income1>{{d.tb1.0}}>>>{{d.compid_report1}}{{d.compname1}}</span>

            <span><a href=#balence1>To balence sheet</a></span>
            {% endif %}
        </form>
        <span><button id=enable>fix column</button></span>
            {% if d.report1 is defined %}

        <div class="row" id=inc>
            <table id="report2" class="display compact nowrap">
                <thead>
                    <tr>
                        <th style="text-align: center">{{d.report1.0.0.0.0|safe}}</th>
                        {% for i in d.report1.0.0|slice:"1:-1" %}
                        <th style="text-align: right;width: 100%;">{{i.0|safe}}</th><th style="text-align: right;;font-size: 14px;">%</th>
                        {% endfor %}
                        <th>Sparklines</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in d.report1.0|slice:"1:" %}
                    <tr>
                        <td><div>{{item.0.0|safe}}</div></td>
                        {% for i in item|slice:"1:-1" %}
                        <td><div style="background-image: linear-gradient( to right, {{i.2|safe}} {{i.1|safe}}%,  #FFF 0px);text-align: right;">{{i.0|safe}}</div></td><td style="text-align: right;font-size: 12px;">{{i.3|safe}}</td>
                        {% endfor %}
                        <td>{{item|slice:"-1"|slice:"0"|safe}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
                </tbody>
            </table>
        </div>

        <!--<span id=balence1>{{d.tb1.1}}>>>{{d.compid_report1}}{{d.compname1}}</span>-->
        <!--<span><a href=#income1>To income statement</a></span>-->
        <!--<div>-->

        <!--</div>-->
    {% endif %}

    {% if d.lspan is defined %}
    {% for item in d.lspan|slice:"1:" %}
    <script type="text/javascript">
    $(function() {

        /* Sparklines can also take their values from the first argument
        passed to the sparkline() function */
        // var myvalues = [10,8,5,null,4,4,1];
        $('.inc{{loop.index}}').sparkline({{item|slice:"1:-1"|safe}}, {width:'100px',height:'25px',    spotColor: undefined,
    minSpotColor: '#00ff00',
    maxSpotColor: '#ff0000'});

    });
    </script>
    {% endfor %}

    {% endif %}

    </div>

    <div id="tabs-10" class="tab-pane">
        <form action = "/rep1/" method = "POST">
            公司代號:<input type="text" name=compid_report1 value=5522>
            <input type="submit" value="query">
            {% if d.report1 is defined %}
            <span id=income1>{{d.tb1.1}}>>>{{d.compid_report1}}{{d.compname1}}</span>

            <span><a href=#balence1>To income statement</a></span>
            {% endif %}
        </form>

        <span><button id=enable1>fix column</button></span>
      {% if d.report1 is defined %}
        <div class="row" id=bal>
            <table id="report3" class="display compact nowrap">

                <thead>
                    <tr>
                        <th style="text-align: center">{{d.report1.1.0.0.0|safe}}</th>
                        {% for i in d.report1.1.0|slice:"1:-1" %}
                        <th style="text-align: right;width: 100%;">{{i.0|safe}}</th><th style="text-align: right;font-size: 14px;">%</th>
                        {% endfor %}
                        <th>Sparklines</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in d.report1.1|slice:"1:" %}
                    <tr>
                        <td><div>{{item.0.0|safe}}</div></td>
                        {% for i in item|slice:"1:-1" %}
                        <td><div style="background-image: linear-gradient( to right, {{i.2|safe}} {{i.1|safe}}%,  #FFF 0px);text-align: right;">{{i.0|safe}}</div></td><td style="text-align: right;font-size: 12px;">{{i.3|safe}}</td>
                        {% endfor %}
                        <td>{{item|slice:"-1"|slice:"0"|safe}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>
      {% endif %}

      {% if d.lspan1 is defined %}
      {% for item in d.lspan1|slice:"1:" %}
      <script type="text/javascript">
      $(function() {

          /* Sparklines can also take their values from the first argument
          passed to the sparkline() function */
          // var myvalues = [10,8,5,null,4,4,1];
          $('.bal{{loop.index}}').sparkline({{item|slice:"1:-1"|safe}}, {width:'100px',height:'25px',    spotColor: undefined,
    minSpotColor: '#00ff00',
    maxSpotColor: '#ff0000'});

      });
      </script>
      {% endfor %}
      {% endif %}
    </div>

djangotest1/mypro/myapp/templates/myapp/testlist0.html
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
<title>Bootstrap Example</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>

<style>

li { list-style-type: none; margin: 0; padding: 0; width: 100%; }

</style>

<script>

function f1(){
$("#div2 ul").append("<li>"+$(this).parent().html()+"</li>");
var x=$('<input type=checkbox name=choice class='+$(this).text()+' value='+$(this).text()+' checked = true>');
$("#div2").append(x);
$(this).parent().remove();
}
function f2(){
$("#div1 ul").append('<li>'+$(this).parent().html()+'</li>');
$("."+$(this).text()+":lt(1)").remove();
$(this).parent().remove();
}

$(document).ready(function(){
    $("#div0 button:eq(0)").click(function(){
        $("#div1 ul").children().remove();
        $("#div1 ul")
        .append("<li><button type='button' class='btn btn-default'>item1</button></li>")
        .append("<li><button type='button' class='btn btn-primary'>item2</button></li>")
        .append("<li><button type='button' class='btn btn-success'>item3</button></li>");

    });

    $("#div0 button:eq(1)").click(function(){
        $("#div1 ul").children().remove();
        $("#div1 ul")
        .append("<li><button type='button' class='btn btn-info'>item4</button></li>")
        .append("<li><button type='button' class='btn btn-warning'>item5</button></li>")
        .append("<li><button type='button' class='btn btn-danger'>item6</button></li>")
        .append("<li><button type='button' class='btn btn-link'>item7</button></li>");
    });

    $("#div1").on('click', 'button', f1);  //$("#div1 button").on('click', f1);  wrong
    $("#div2").on('click', 'button', f2);  //$("#div2 button").on('click', f2);  wrong

    $("ul").sortable({
     cancel: ".fixed"
    });

});

</script>

</head>

<body>

<div class="row">
    <div id='div0' style="background-color:pink;color:white;padding:10px;" class="col-md-4">
        <button>1</button>
        <button>2</button>
    </div>

    <div id='div1' style="background-color:purple;color:white;padding:10px;" class="col-md-4">
        <ul></ul>
    </div>
    <form action="{% url 'myapp:test'%}" method="post">
        {% csrf_token %}
        <div id='div2' style="background-color:black;color:white;padding:10px;" class="col-md-4">
            <ul></ul>
        </div>
        <input type="submit">
    </form>


</div>

    {% for item in l %}
    {{ item }}<br>
    {% endfor %}

    <form action="{% url 'myapp:listfield'%}" method="post">
        {% csrf_token %}
        <h4>mops</h4>
        {% for item in mops %}
        <input type="radio" name=dbtable value={{ item }}>{{ item }}<br>
        {% endfor %}
        <h4>mysum</h4>
        {% for item in mysum %}
        <input type="radio" name=dbtable value={{ item }}>{{ item }}<br>
        {% endfor %}
        <h4>summary</h4>
        {% for item in summary %}
        <input type="radio" name=dbtable value={{ item }}>{{ item }}<br>
        {% endfor %}
        <h4>tse</h4>
        {% for item in tse %}
        <input type="radio" name=dbtable value={{ item }}>{{ item }}<br>
        {% endfor %}
        <input type="submit" value="Show fields">
    </form>

</body>
</html>

djangotest1/mypro/myapp/templates/myapp/ys.html
<!-- Load c3.css -->

<link rel="stylesheet" href="../static/c3/c3-0.4.11/c3.css">
<!-- <script type="text/javascript" src="../static/bower_components/c3/c3.min.css"></script> -->

<!-- Load d3.js and c3.js -->
<!-- need d3.v3 -->
<!-- <script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script> -->
<script type="text/javascript" src="../static/d3.v3/d3.v3.min.js"></script>
<!-- <script type="text/javascript" src="../static/bower_components/d3/d3.min.js"></script> -->
<script type="text/javascript" src="../static/bower_components/c3/c3.min.js"></script>
<!-- <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script> -->

{% for l in d.mllys %}
<div id = chart{{l.0|safe}} class=inline></div>
    <form action = "/remove/" method = "POST">
        <input type="submit" name=c3{{l.0|safe}} value="X" class='remove inline'>
    </form>
{% endfor %}

{% for l in d.mllys %}
    <script>

    var chart = c3.generate({
        bindto: '#chart{{l.0|safe}}',
        data: {
            x: '年月日',
            rows:
                {{l.1|safe}}
        },
        subchart: {
            show: false
        },
        size: {
            width:750,
            height: 300
        },
        point: {
            show: false
        },
        title: {
            text: {{l.2|safe}}
        },
        axis: {
            x: {
                type: 'timeseries',
                tick: {
                    format: '%Y-%m'
                }
            }
        }
    });


    </script>
{% endfor %}